export const ROUTES = {
  home: '/',
  agent: '/agent',
  hospitals: '/hospitals',
  hospitalDetail: '/hospitals/:hospitalId',
  doctors: '/doctors',
  doctorDetail: '/doctors/:doctorId',
  appointments: '/appointments',
  appointmentDetail: '/appointments/:appointmentId',
  about: '/about',
  help: '/help',
  contact: '/contact',
  reviews: '/reviews',
  login: '/login',
  register: '/register',
  profile: '/profile',
  documents: '/documents',
} as const;
